# Generated by Django 5.2.4 on 2025-08-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=3)),
                ('is_Active', models.BooleanField(default=False)),
            ],
        ),
    ]
